# Site settings
title: I4INFO
header-img: img/home-bg.jpg
email: heeraj123@gmail.com
description: "Blog by a common man!!!"
baseurl: ".."
url: "https://heeraj.com/blog/"
twitter_username: heerajnair
github_username:  h33raj
facebook_username:  heeraj123

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 7
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

layout: default
comments: true
